### PR TITLE
compile mapgen with cmake

### PR DESCRIPTION
**Pull request by mdhender**

### CODE REVIEW

**Comment by jrolder** [comment]
Hey Michael - this is quite the blast from the past! Very happy to see you picking up the torch on olympia. Do you have plans to run a game at some point?

As writing turns is so painful, I've always wanted to rebuild Oly-TAG as a modern interactive browser app, but never found the time to do it.

**Comment by jrolder** [comment]
Why did you close your PRs? Would have been happy to accept them. Also happy to point to your fork from here if that would make sense. Looks like you've done a lot more work on the code than I have.

**Comment by mdhender** [comment]
Hi! Thank you for creating this repo. Great place to start from.

I've got `mapgen` working on 32- and 64- bit systems. Just about to tackle the main command.

I closed the PRs because I saw that they were rolling up in a really odd way. I'm going to create a new one today to see if I can fix that.

Yes, I'd like to set up a server and run a game.

**Comment by mdhender** [comment]
Closed - overtaken by PR #4

**Comment by jrolder** [comment]
Cool - let me know when you start recruiting players! I'd like to join.

These guys ran the last oly-tag game I'm aware of back in 2019: https://www.pbem-spiele.de/

Might be a good place to recruit players - I can help with the language.

**Pull request closed without merging**
